Solution/arrays and loop
tul1/edouard_training pull request #1
Opened 2024-10-19 07:37 UTC by busin11

1 - Created file 
2 - Edited README

2024-10-19 09:21 UTC, tul1 requested changes
not bad but it needs some rework.

2024-10-19 09:21 UTC, tul1 commented on README.md
> +Via le chemin relatif j’execute ce qui suit : go run arrays_and_loops.go (compilation + execution) go
Translate to English please.

2024-10-19 09:21 UTC, tul1 commented on arrays_assignment.go
are you using vscode? if you do something is wrong with you setup because there should be a tabulation at every curly bracket level.

2024-10-19 09:21 UTC, tul1 commented on arrays_assignment.go
> +var ode string
```suggestion
var odd string
```

2024-10-19 09:21 UTC, tul1 commented on arrays_assignment.go
> +if(arr[i]%2==1){ode="odd"}else{ode="even"}
this is not perl, in go we don't like inline if else. the correct styling should be:
```
if arr[i]%2==1 {
    ode="odd"
} else {
    ode="even"
}
```

2024-10-19 09:21 UTC, tul1 commented on README.md
can you explain in the readme how the code works? I need to check that you understand the key algorithmic topics of this exercice. For example, explain to me how the `%` works.

2024-10-19 09:21 UTC, tul1 commented on arrays_assignment.go
> +fmt.Printf("Element %v : %v , Square : %v , %v", i+1, arr[i],
replace the verb `%v` for the appropriated verb type.

2024-10-19 09:33 UTC, busin11 commented on arrays_assignment.go
for sure i do, let me fix  my env asap, kk i'll rework this copy

2024-10-19 10:35 UTC, busin11 commented on README.md
> +Via le chemin relatif j’execute ce qui suit : go run arrays_and_loops.go (compilation + execution) go
done

2024-10-19 10:35 UTC, busin11 commented on arrays_assignment.go
> +var ode string
done

2024-10-19 10:36 UTC, busin11 commented on arrays_assignment.go
> +if(arr[i]%2==1){ode="odd"}else{ode="even"}
kk, done too.
i'll reminds me that for next steps.

2024-10-19 10:38 UTC, busin11 commented on README.md
done
i'll fix lang in other branches/exercices and let you know when its ok.
Also, i'll try to do better algorithmic files in next exercices.

2024-10-19 10:38 UTC, busin11 commented on arrays_assignment.go
> +fmt.Printf("Element %v : %v , Square : %v , %v", i+1, arr[i],
done

2024-10-20 11:48 UTC, tul1 commented
You have modified the wrong README file and added your code on the `/` path of the project. This isn't correct, you should update the `/arrays_and_loops/README.md` and add the go file in the folder too.

2024-10-20 12:07 UTC, tul1 requested changes
still some organisation modifications are required to move forward.

2024-10-20 12:07 UTC, tul1 commented on arrays_assignment.go
the indentation is still not correct. I've create a gist to show you the correct way: https://gist.github.com/tul1/c8e22d290534c3197c3b9d478ff1b782

2024-10-20 16:46 UTC, busin11 commented on README.md
> +package main // define package
I agree with you, lets fix some basics on my side.
i apologise for the delay, works will be done before tomorrow.

2024-10-20 16:58 UTC, busin11 commented on arrays_assignment.go
> +	fmt.Printf("\nElement %#v	: %#v, Square : %#v , %#v", i+1, arr[i],
in maths functions, output are sensibles so we can't pretend to recover all time what we want to 
NaN (Not a Number : greater than, less than ...), ex. [-∞,2[ (+/- infinite)
%#v is a go representation for values and it prints NaN and +Inf

2024-10-20 19:16 UTC, tul1 commented on arrays_assignment.go
> +	fmt.Printf("\nElement %#v	: %#v, Square : %#v , %#v", i+1, arr[i],
For representing `int` and `float` values, I suggest using the `%d` and `%f` verbs instead of `%v`. While `%v` works as a catch-all, using the specific format verbs makes it easier for the compiler, as it won’t need to infer the type. Additionally, it improves the readability of your code, making it clear to others what type of value is being formatted.

2024-10-20 23:03 UTC, tul1 commented
why are you keeping this pull request open?

2024-10-20 23:35 UTC, closed without merging