Add solution & readme to structs_public_and_private_methods
tul1/edouard_training pull request #14
Opened 2024-10-23 20:57 UTC by busin11

1- Add file: structs_public_and_private_methods.go
2- Edit README.md

2024-10-24 08:24 UTC, tul1 requested changes

2024-10-24 08:24 UTC, tul1 commented on structs_public_and_private_methods/README.md
> +
what are the advantages of defining fields of the Object Person with private visibility?

2024-10-24 08:24 UTC, tul1 commented on structs_public_and_private_methods/structs_public_and_private_methods.go
> +func (p Person) isAdult() bool {
In the definition of a method of an Object in golang you must define its receiver which is this part of the definition:`(p Person)`. The receiver specifies that the method `isAdult` is associated with the `Person` type, meaning it can be called on any instance of Person. There are 2 kind of receivers: Value receiver and Pointer receiver. We'll do an exercice later to see the difference between the two.

2024-10-24 08:54 UTC, busin11 commented on structs_public_and_private_methods/structs_public_and_private_methods.go
> +func PrintInfo(p1 Person) {
Forgot, will be fix with next commit.

2024-10-24 08:54 UTC, busin11 commented on structs_public_and_private_methods/README.md
> +1- Initialize Person struct with firstName, lastName string & age int
Uppercase ?

2024-10-24 08:55 UTC, busin11 commented on structs_public_and_private_methods/structs_public_and_private_methods.go
> +ackage main
Will be fix with next commit.

2024-10-24 09:16 UTC, busin11 commented on structs_public_and_private_methods/README.md
> +1- Initialize Person struct with firstName, lastName string & age int
Uppercase: public ?
Lowercase: private ?

2024-10-24 09:19 UTC, tul1 commented on structs_public_and_private_methods/README.md
> +1- Initialize Person struct with firstName, lastName string & age int
Correct

2024-10-24 14:25 UTC, tul1 commented on structs_public_and_private_methods/README.md
> +
Actually, in Go, nothing is "loaded" when fields are private; the fields are just inaccessible outside the package. The key benefits of making struct fields private are:
* Encapsulation: You control how the data is accessed or modified through public methods, preventing direct changes.
* Validation: You can enforce rules (like ensuring age is positive) when setting values.
* Flexibility: It allows you to change internal details later without affecting the rest of your code, keeping things maintainable.

Making fields private is about controlling access and ensuring consistency, not about delaying when things are loaded.

2024-10-25 18:15 UTC, busin11 commented
PR is mergeable.

2024-10-25 20:51 UTC, tul1 commented on structs_public_and_private_methods/structs_public_and_private_methods.go
> +func (p1 Person) PrintInfo() {
```suggestion
func (p Person) PrintInfo() {
```

2024-10-25 20:51 UTC, tul1 commented on structs_public_and_private_methods/structs_public_and_private_methods.go
> +        if p1.isAdult() {
```suggestion
        if p.isAdult() {
```

2024-10-25 20:51 UTC, tul1 commented on structs_public_and_private_methods/structs_public_and_private_methods.go
> +                fmt.Printf("%s isn't an adult\n", p1.firstName)
```suggestion
                fmt.Printf("%s isn't an adult\n", p.firstName)
```

2024-10-25 20:52 UTC, tul1 commented on structs_public_and_private_methods/structs_public_and_private_methods.go
> +                fmt.Printf("%s is an adult", p1.firstName)
```suggestion
                fmt.Printf("%s is an adult", p.firstName)
```

2024-10-25 20:52 UTC, tul1 commented on structs_public_and_private_methods/structs_public_and_private_methods.go
> +        fmt.Printf("Full Name: %s %s, age: %d", p1.firstName, p1.lastName, p1.age)
```suggestion
        fmt.Printf("Full Name: %s %s, age: %d", p.firstName, p.lastName, p.age)
```

2024-10-25 20:52 UTC, tul1 commented on structs_public_and_private_methods/structs_public_and_private_methods.go
> +                fmt.Printf("%s isn't an adult\n", p1.firstName)
```suggestion
                fmt.Printf("%s isn't an adult\n", p.firstName)
```

2024-10-25 20:54 UTC, tul1 requested changes
Don't need to rename the receiver.

2024-10-26 08:28 UTC, tul1 approved these changes
LGTM

2024-10-26 09:15 UTC, merged