Add solution & readme to solution/maps
tul1/edouard_training pull request #16
Opened 2024-10-25 19:55 UTC by busin11

1- Add file: hashmap.go
2- Edit README.md

2024-10-26 08:44 UTC, tul1 requested changes

2024-10-26 08:44 UTC, tul1 commented on maps/hashmap.go
> +	m := make(map[string]int)
since you already already know the side of the map, can you predefine it while you construct it with the `make`?

2024-10-26 08:44 UTC, tul1 commented on maps/hashmap.go
> +	m["bananas"] += 1
can you explain in the readme how the `+=` and the `-=` operation works?

2024-10-27 19:23 UTC, busin11 commented on maps/hashmap.go
> +	m["bananas"] += 1
m["bananas"] += 1 is equivalent to m["bananas"] = m["bananas"] +1 ?
m["bananas"] -= 1 is equivalent to m["bananas"] = m["bananas"] - 1 ?

2024-10-27 19:36 UTC, busin11 commented on maps/hashmap.go
> +	m := make(map[string]int)
var m map[string]int ?

Maybe i didn't understand your question.

2024-10-28 09:11 UTC, tul1 commented on maps/hashmap.go
> +	m["bananas"] += 1
correct!

2024-10-28 14:33 UTC, tul1 commented on maps/hashmap.go
> +	m := make(map[string]int)
sorry my comment was misspelled, I meant: if you already know the size of the map that you are going to use you can already request the size of it with `make`. 

The answer is that in Go, you can specify the capacity of the map when you create it like this:
```go
m := make(map[string]int, size)
```
 If you know how many elements the map will have, this approach can help optimize memory allocation and improve efficiency, especially if the map will store many items.

2024-11-13 20:53 UTC, busin11 commented
i checked again and normally changes requested are done.

2024-11-21 20:10 UTC, tul1 approved these changes

2024-11-21 20:12 UTC, merged