Arrays and loops
tul1/edouard_training pull request #8
Opened 2024-10-20 18:27 UTC by busin11

1- Created arrays_and_loops.go file
2- Edited README

2024-10-20 19:10 UTC, tul1 requested changes
not there yet, but you are getting closer.

2024-10-20 19:10 UTC, tul1 commented on arrays_and_loops/README.md
> +How It Works
can you add how to run it with `test.txt` file you've added?

2024-10-20 19:10 UTC, tul1 commented on arrays_and_loops/arrays_and_loop.go
> +	for i:=0;i<len(arr);i++ {
This isn't the best way to use `for` statement in golang. probably the most golanguintisc way is this one:
```suggestion
	for i := range arr {
```

Can you update the code to use the suggested form?

2024-10-20 19:10 UTC, tul1 commented on arrays_and_loops/test.txt
> +Element: " Square: %#v %#v" 1%!(EXTRA int=0, float64=0, string=even)Element: " Square: %#v %#v" 2%!(EXTRA int=1, float64=1, string=odd)Element: " Square: %#v %#v" 3%!(EXTRA int=4, float64=2, string=e
what is the propose of this file?

2024-10-20 19:10 UTC, tul1 commented on arrays_and_loops/arrays_and_loop.go
> +		fmt.Print("\nElement ", i+1, ": ", arr[i], ",  Square: ", math.Sqrt(float64(arr[i])), ", ",  odd, "\n")
Golang is types language, this means that variables are types. for example, `arr` is an array of `int` or `odd` is a `string`. To be printed each type have a formatting verb (doc [link](https://pkg.go.dev/fmt)). can you use the correct verb for the element that you want to print using `Printf` like you did in the other PR?

2024-10-20 19:10 UTC, tul1 commented on hello_world/README.md
> +compilation:
This patch belong to another branch and another PR. Let's keep the commit history clean.

2024-10-20 20:08 UTC, busin11 commented on arrays_and_loops/arrays_and_loop.go
> +	for i:=0;i<len(arr);i++ {
for sure, you're right why define a loop to iterate over an array if i have 'range' func used for

2024-10-20 20:10 UTC, busin11 commented on arrays_and_loops/test.txt
> +Element: " Square: %#v %#v" 1%!(EXTRA int=0, float64=0, string=even)Element: " Square: %#v %#v" 2%!(EXTRA int=1, float64=1, string=odd)Element: " Square: %#v %#v" 3%!(EXTRA int=4, float64=2, string=e
a test for output result in %#v verb 
not really useful, juste for my comprehension

2024-10-20 21:15 UTC, busin11 commented on arrays_and_loops/README.md
> +Array Squaring and Even/Odd Identifier
done

2024-10-20 21:15 UTC, busin11 commented on arrays_and_loops/README.md
> +How It Works
done ; not necessary cause its not a valid file for this assignment

2024-10-20 21:15 UTC, busin11 commented on arrays_and_loops/arrays_and_loop.go
> +		fmt.Print("\nElement ", i+1, ": ", arr[i], ",  Square: ", math.Sqrt(float64(arr[i])), ", ",  odd, "\n")
done

2024-10-20 22:14 UTC, busin11 commented
I might need your help cause i've added a pull request with strings_and_functions to add solution and edited readme but when i'am moving to commit sections of pull request it displays me previous commit too.

i'll look deeper into the functionning of git.

2024-10-20 23:02 UTC, tul1 requested changes
revert the changes in hello_world/README.md and address the other comment and we'll be done :).

2024-10-20 23:02 UTC, tul1 commented on arrays_and_loops/README.md
> +4- at each iteration check if modulo 2 of array index is 0 or not, if 0 then associate odd string value to odd var else associate even value to odd var
```suggestion
4- at each iteration it check if the element of the array is even or odd. If `arr[i]%2==1` is true means that the number is odd. Complementary If `arr[i]%2==1` is false the number is pair (or even).
```

2024-10-20 23:02 UTC, tul1 commented on arrays_and_loops/arrays_and_loop.go
> +		fmt.Printf("Element %d: %d , Square %#v , %s", i+1, arr[i], math.Sqrt(float64(arr[i])), odd+"\n")
```suggestion
		fmt.Printf("Element %d: %d , Square %f , %s\n", i+1, arr[i], math.Sqrt(float64(arr[i])), odd) 
```

2024-10-20 23:48 UTC, busin11 commented on arrays_and_loops/README.md
> +Array Squaring and Even/Odd Identifier
i will check why env is not set correctly

2024-10-21 07:49 UTC, tul1 commented on hello_world/README.md
> +'''
```suggestion
```bash
```

2024-10-21 07:50 UTC, tul1 commented on hello_world/README.md
> +'''
```suggestion
```
```

2024-10-21 07:50 UTC, tul1 commented on hello_world/README.md
> +'''
```suggestion
```
```

2024-10-21 07:50 UTC, tul1 commented on hello_world/README.md
> +'''
```suggestion
```
```

2024-10-21 07:50 UTC, tul1 commented on hello_world/README.md
> +'''
```suggestion
```bash
```

2024-10-21 07:50 UTC, tul1 commented on hello_world/README.md
> +'''
```suggestion
```
```

2024-10-21 17:53 UTC, busin11 commented
You've askied me to use the next command in order to not commit previous changes in PR in another PR : "git pull origin main_or_branch --rebase", but it doesn't works for me, maybe i didnt do the right thing ; also i've to set up correctly my env to be sure to work efficently.

I purpose you to send you emails with my assignment solutions & readme for tomorrow ?

2024-10-22 10:13 UTC, tul1 commented on arrays_and_loops/arrays_and_loop.go
> +		var odd string
```suggestion
		var pairity string
```

2024-10-22 16:34 UTC, busin11 commented
Let me know when i can merge and create another PR for next assignment.

2024-10-23 15:19 UTC, merged